### ISSUE TITLE
can't run main_seq.py

### ISSUE THREAD

**Issue by gzpbbd** [cszmli/Rethink-RL-Sup#1]
When I run 
`python -u main_seq.py  --load model_seq/test/best --lr_rl 1e-4 --lr_irl 1e-4 --epoch 80 --gen_type beam --avg_type  real_word --policy_clip 0.5 --activate_type no --cat_mlp True`

The program didn't output anything after outputing:
`DEBUG:root:start loading seq train`

**Comment by ShuoZhangXJTU** [comment]
The dataset provided in his download url doesn't conclude the data for DiaSeq.
The program is generating it, but it takes looooong time to run that's it

**Comment by ShuoZhangXJTU** [comment]
The dataset provided in his download url doesn't include the data for DiaSeq.
The program is generating it, but it takes looooong time to run that's what happening

**Comment by gzpbbd** [comment]
> The dataset provided in his download url doesn't include the data for DiaSeq.
> The program is generating it, but it takes looooong time to run that's what happening

you're right. thank you.
